export const list = [
 {name: "---", value: "default", codeTypes: ["banner", "inpage", "instream", "combo"]},
 {name: "Criteo", value: "criteo", codeTypes: ["banner"]},
 {name: "Soloway", value: "adriver", requireSizes: true, codeTypes: ["banner", "inpage", "instream"]},
 {name: "HPMD", value: "hpmd", codeTypes: ["banner"]},
 {name: "Buzzoola", value: "buzzoola", codeTypes: ["banner", "inpage"]},
 {name: "Mytarget", value: "myTarget", codeTypes: ["banner"]},
 {name: "Facebook", value: "facebook", codeTypes: ["banner"]},
 {name: "Between Digital", value: "betweenDigital", codeTypes: ["banner", "inpage", "instream"]},
 {name: "All in One Media", value: "aio", codeTypes: ["banner"]},
 {name: "GetIntent", value: "getintent", codeTypes: ["banner"]},
 {name: "Tinkoff", value: "tinkoff", codeTypes: ["banner"]},
 {name: "Videonow", value: "videonow", codeTypes: ["banner"]},
 {name: "RTB House", value: "rtbhouse", codeTypes: ["banner"]},
 {name: "Relap", value: "relap", codeTypes: ["banner"]},
 {name: "Pladform", value: "pladform", codeTypes: ["banner"]},
 {name: "Alfasense", value: "alfasense", codeTypes: ["banner"]},
 {name: "Fotostrana", value: "fotostrana", codeTypes: ["banner"]},
 {name: "Hybrid", value: "hybrid", codeTypes: ["banner", "inpage"]},
 {name: "Mgid", value: "mgid", codeTypes: ["banner"]},
 {name: "DGT SSP", value: "dgt_ssp", codeTypes: ["banner"]},
 {name: "ADSPEND", value: "adspend", codeTypes: ["banner", "inpage"]},
 {name: "MediaToday", value: "mediatoday", codeTypes: ["banner", "inpage"]},
 {name: "Redllama", value: "redllama", codeTypes: ["banner", "inpage"]},
 {name: "Qvant DSP", value: "qvant_dsp", codeTypes: ["banner", "inpage"]},
 {name: "ADFOX HB", value: "adfox", codeTypes: ["banner", "inpage", "instream", "combo"]}
];