export const list = {
  "default": {value: "---", codeTypes: ["banner", "inpage", "instream", "combo"]},
  "criteo":  {value: "Criteo", codeTypes: ["banner"]},
  "adriver": {value: "Soloway", requireSizes: true, codeTypes: ["banner", "inpage", "instream"]},
  "hpmd": {value: "HPMD", codeTypes: ["banner"]},
  "buzzoola": {value: "Buzzoola", codeTypes: ["banner", "inpage"]},
  "myTarget": {value: "Mytarget", codeTypes: ["banner"]},
  "facebook": {value: "Facebook", codeTypes: ["banner"]},
  "betweenDigital": {value: "Between Digital", codeTypes: ["banner", "inpage", "instream"]},
  "aio": {value: "All in One Media", codeTypes: ["banner"]},
  "getintent": {value: "GetIntent", codeTypes: ["banner"]},
  "tinkoff": {value: "Tinkoff", codeTypes: ["banner"]},
  "videonow": {value: "Videonow", codeTypes: ["banner"]},
  "rtbhouse": {value: "RTB House", codeTypes: ["banner"]},
  "relap": {value: "Relap", codeTypes: ["banner"]},
  "pladform": {value: "Pladform", codeTypes: ["banner"]},
  "alfasense": {value: "Alfasense", codeTypes: ["banner"]},
  "fotostrana": {value: "Fotostrana", codeTypes: ["banner"]},
  "hybrid": {value: "Hybrid", codeTypes: ["banner", "inpage"]},
  "mgid": {value: "Mgid", codeTypes: ["banner"]},
  "dgt_ssp": {value: "DGT SSP", codeTypes: ["banner"]},
  "adspend": {value: "ADSPEND", codeTypes: ["banner", "inpage"]},
  "mediatoday": {value: "MediaToday", codeTypes: ["banner", "inpage"]},
  "redllama": {value: "Redllama", codeTypes: ["banner", "inpage"]},
  "qvant_dsp": {value: "Qvant DSP", codeTypes: ["banner", "inpage"]},
  "adfox": {value: "ADFOX HB", codeTypes: ["banner", "inpage", "instream", "combo"]}
};